### ISSUE TITLE
abrupt stop

### ISSUE THREAD

**Issue by ChristophTobler** [zehortigoza/aero-optical-flow#5] opened 2017-04-26 08:27 UTC
The flow app stops mostly after some time (sometimes earlier, sometimes later).
@zehortigoza Have you had the same issue?

**Comment by zehortigoza** [comment] 2017-04-26 17:52
I had some times but every-time that it happens I don't have GDB connected to debug, 99% sure that is because badly ported ISP driver.
I will try some workarounds to restart the video streaming after 2 times of the period between 2 frames.

**Comment by zehortigoza** [comment] 2017-05-04 01:16
Workaround implemented the problem is the atomisp driver, as we already have a issue on https://github.com/intel-aero/meta-intel-aero to update the atomisp driver I'm closing this issue.

**Closed as completed by zehortigoza** 2017-05-04 01:16 UTC

**Comment by ChristophTobler** [comment] 2017-06-19 07:26
Is this still being tracked? I can't find the issue in https://github.com/intel-aero/meta-intel-aero/issues

**Comment by zehortigoza** [comment] 2017-06-19 22:46
> Is this still being tracked? I can't find the issue in https://github.com/intel-aero/meta-intel-aero/issues

Is this one: https://github.com/intel-aero/meta-intel-aero/issues/64
